snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: biuptny-bb70598
      user: VICTORHOP
      password: Vitor%1000
      database: DB_ADVENTUREWORKS
      role: ACCOUNTADMIN
      schema: RAW_SCHEMA
      threads: 4
      warehouse: AW_WAREHOUSE
