version: 2

sources:
  - name: adventureworks
    description: Data originating from the sandbox in Snowflake.
    database: DB_ADVENTUREWORKS
    schema: RAW_SCHEMA
    tables:
      - name: employee
        description: "This model contains user data with detailed information about their employees."
